### ISSUE TITLE
Ensure that interaction between CLI tool and scripts allows logging to function as intended

### ISSUE THREAD

**Issue by juliusgeo** [mongodb-labs/pymongoexplain#13]

**Comment by prashantmital** [comment]
At the very least, we need to document the implications of the CLI tool configuring logging to produce explain output. I think any logging configured by the script would override the configuration performed by the CLI tool - we need to confirm this and document it in the README.

At the very least, the README should mention that the CLI tool configures logging so if the script also does that it might result in some unexpected/unintuitive interactions.
