### ISSUE TITLE
Discrepancy between submodule name and ExplainCollection classname

### ISSUE THREAD

**Issue by prashantmital** [mongodb-labs/pymongoexplain#31]
I am not sure how we missed this, but it seems odd that `ExplainCollection` is in a file called `explainable_collection.py`. Should we fix this discrepancy?

**Comment by prashantmital** [comment]
I guess this would be a breaking change so it now needs to wait until 2.0? Thoughts? @ShaneHarvey @juliusgeo

**Comment by juliusgeo** [comment]
Yeah, I just noticed that as well when writing the elevator pitch. I think that as long as we update the documentation it could be incorporated into 1.1

**Comment by ShaneHarvey** [comment]
One option would be to rename the class to `ExplainableCollection` and add an `ExplainCollection` alias to preserve backwards compatibility.

**Comment by prashantmital** [comment]
I like this idea of naming the class `ExplainableCollection` and adding an alias. @juliusgeo please implement this change. Remember that you will need to add the `ExplainableCollection` class to the `__init__.py` namespace as well to make it importable directly from the module!
